### ISSUE TITLE
Doesn't work when used with "express.json" middleware

### ISSUE THREAD

**Issue by nnnnat** [mswjs/http-middleware#18]
Hey y'all big fan of MSW! 

I've been using MSW & http-middleware together to create a mock GraphQL API for a few months & I've recently run into an issue after updating to MSW v0.44.2 & http-middleware v0.5.0. I have a very similar setup to the [custom server](https://github.com/mswjs/http-middleware/blob/main/examples/custom-server.ts) example in this repo & after updating all GQL operations now seem to pass through & return a 404 "Mock not found". 

I've put together a [small example](https://github.com/nnnnat/msw-middleware-example) that reproduces the issue I'm seeing.

**Comment by kettanaito** [comment]
Hey, @nnnnat. Thanks for raising this.

I've taken a quick look and it seems that the body we encode in the middleware results in the encoded `"[object Object]"` _string_. When MSW attempts to parse that body, it treats it as a string, so it doesn't pass as a valid GraphQL API request. 

I believe the issue is somewhere around here:

https://github.com/mswjs/http-middleware/blob/ca849760dd3e32e990d33d66d393c101e5dc1f02/src/middleware.ts#L22

**Comment by kettanaito** [comment]
## Released: v0.5.1 🎉

This has been released in v0.5.1!

- 📄 [**Release notes**](https://github.com/mswjs/http-middleware/releases/tag/v0.5.1)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/http-middleware/v/0.5.1)

Make sure to always update to the latest version (`npm i @mswjs/http-middleware@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
