### ISSUE TITLE
Peer dependencies too strict?

### ISSUE THREAD

**Issue by fvanwijk** [mswjs/http-middleware#2]
This package has msw@^0.33.0  as peer dependency.
This means that you cannot use it in your project if you have a lower `msw` version as devDependency.

Doesn't it really work with a lower version of msw? I think you could make the peer deps less strict.
Test the application with the lowest MSW version possible and set that as peer dep, for example `>=0.25`.

**Comment by kettanaito** [comment]
Hey, @fvanwijk.

> Doesn't it really work with a lower version of msw?

It doesn't. We've refined the public API of MSW to allow an extension like this to work. In more detail, we've exported the `handleRequest` function publicly, that's the same function that is used in MSW to resolve a mocked response. This means that `http-middleware` reuses the exact logic that MSW uses during response resolution. Such API simply doesn't exist in the older versions of MSW, so you cannot use them as a peer dependency of `http-middleware`.

In general, I'm considering setting `msw: latest` as the dependency, because you're absolutely always want to be on the latest version of MSW. I acknowledge that issues may happen, and regressions may occur, but that doesn't mean you shouldn't be using the latest tech, as it also includes new features and fixes. If anything, the more people use the latest version the faster its issues are going to be addressed (or even contributed to by other people in a proper open-source way).
